# Generated by ei from examples/report.ei
# Each comment shows the source statement.

import pandas as pd
import matplotlib.pyplot as plt

# load the csv file sales.csv
df = pd.read_csv("sales.csv")

# parse the date column as dates
df["date"] = pd.to_datetime(df["date"])

# keep only the rows from 2024
df = df[df["date"].dt.year == 2024]

# group by region and sum the revenue
result = df.groupby("region")["revenue"].sum()

# sort by revenue, largest first
result = result.sort_values(ascending=False)

# plot the result as a bar chart with the title "Sales 2024 by region"
ax = result.plot.bar(title="Sales 2024 by region")
plt.tight_layout()

# save the chart as sales_2024.png
plt.savefig("sales_2024.png")

# print the top 3 regions with their revenue
print(result.head(3))
